@startuml packages_marketscout
set namespaceSeparator none
package "api" as api {
}
package "api.brokerage" as api.brokerage {
}
package "api.brokerage.client" as api.brokerage.client {
}
package "api.ib" as api.ib {
}
package "api.ib_api_exception" as api.ib_api_exception {
}
package "api.ib_app" as api.ib_app {
}
package "api.ib_utils" as api.ib_utils {
}
package "app" as app {
}
package "backtesting" as backtesting {
}
package "backtesting.data_processor" as backtesting.data_processor {
}
package "backtesting.visualization" as backtesting.visualization {
}
package "handlers" as handlers {
}
package "handlers.ib_handler" as handlers.ib_handler {
}
package "ib_async_example" as ib_async_example {
}
package "models" as models {
}
package "models.indicator" as models.indicator {
}
package "models.order" as models.order {
}
package "models.portfolio" as models.portfolio {
}
package "models.position" as models.position {
}
package "models.starter" as models.starter {
}
package "models.strategies" as models.strategies {
}
package "models.strategies.base_strategy" as models.strategies.base_strategy {
}
package "models.strategies.pairs_trading" as models.strategies.pairs_trading {
}
package "models.strategies.rule" as models.strategies.rule {
}
package "utils" as utils {
}
package "utils.cli" as utils.cli {
}
package "utils.cli.callbacks" as utils.cli.callbacks {
}
package "utils.cli.cli" as utils.cli.cli {
}
package "utils.cli.cli_exceptions" as utils.cli.cli_exceptions {
}
package "utils.logging_utils" as utils.logging_utils {
}
package "utils.references" as utils.references {
}
api.brokerage.client --> api.ib_api_exception
api.brokerage.client --> api.ib_utils
api.brokerage.client --> utils.references
api.ib --> api.brokerage.client
api.ib --> api.ib_api_exception
api.ib --> api.ib_utils
api.ib --> utils.cli.cli
api.ib --> utils.references
api.ib_utils --> api.ib_api_exception
api.ib_utils --> utils.references
app --> api.ib
app --> api.ib_utils
app --> models.order
app --> utils.cli.callbacks
app --> utils.cli.cli
app --> utils.references
models.order --> utils.references
models.starter --> models.indicator
models.strategies.pairs_trading --> models.strategies.base_strategy
models.strategies.rule --> models.indicator
utils.cli.callbacks --> utils.cli.cli
utils.cli.callbacks --> utils.references
utils.cli.cli --> utils.logging_utils
utils.cli.cli --> utils.references
@enduml
