"""add open/close dates, prices, and instrument info to Trade

Revision ID: 60ad89712827
Revises: cbc0d67b3c98
Create Date: 2025-04-07 13:44:13.685230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ad89712827'
down_revision = 'cbc0d67b3c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_date', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=False))
        batch_op.add_column(sa.Column('close_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('instrument_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('product_type', sa.String(length=50), nullable=False))
        batch_op.drop_index('ix_trade_date')
        batch_op.create_index(batch_op.f('ix_trade_close_date'), ['close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_instrument_name'), ['instrument_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_open_date'), ['open_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_product_type'), ['product_type'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_trade_product_type'))
        batch_op.drop_index(batch_op.f('ix_trade_open_date'))
        batch_op.drop_index(batch_op.f('ix_trade_instrument_name'))
        batch_op.drop_index(batch_op.f('ix_trade_close_date'))
        batch_op.create_index('ix_trade_date', ['date'], unique=False)
        batch_op.drop_column('product_type')
        batch_op.drop_column('instrument_name')
        batch_op.drop_column('close_price')
        batch_op.drop_column('close_date')
        batch_op.drop_column('open_price')
        batch_op.drop_column('open_date')

    # ### end Alembic commands ###
