"""empty message

Revision ID: 6646c01687d7
Revises: b40e249344e7
Create Date: 2024-10-15 13:40:42.002773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6646c01687d7'
down_revision = 'b40e249344e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profit_and_loss.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_user_id'))
        batch_op.drop_index(batch_op.f('ix_trade_owner_id'))
        batch_op.drop_index(batch_op.f('ix_trade_date'))

    op.drop_table('trade')
    # ### end Alembic commands ###
