"""initial db migration

Revision ID: 9a43e2891ead
Revises: 
Create Date: 2025-05-10 11:23:39.009124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a43e2891ead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_researcher_researcher_name'), ['researcher_name'], unique=True)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['researcher.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('profit_and_loss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('fk_profit_and_loss_researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_profit_and_loss_researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('instrument_name', sa.String(length=50), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('fk_profit_and_loss_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_profit_and_loss_id'], ['profit_and_loss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_close_date'), ['close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_fk_profit_and_loss_id'), ['fk_profit_and_loss_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_instrument_name'), ['instrument_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_open_date'), ['open_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_product_type'), ['product_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_product_type'))
        batch_op.drop_index(batch_op.f('ix_trade_open_date'))
        batch_op.drop_index(batch_op.f('ix_trade_instrument_name'))
        batch_op.drop_index(batch_op.f('ix_trade_fk_profit_and_loss_id'))
        batch_op.drop_index(batch_op.f('ix_trade_close_date'))

    op.drop_table('trade')
    op.drop_table('profit_and_loss')
    op.drop_table('followers')
    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_researcher_name'))
        batch_op.drop_index(batch_op.f('ix_researcher_email'))

    op.drop_table('researcher')
    # ### end Alembic commands ###
