"""empty message

Revision ID: f1b037449f37
Revises: 
Create Date: 2025-03-21 22:31:22.458321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b037449f37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_and_loss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('researcher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('researcher_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_researcher_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_researcher_researcher_name'), ['researcher_name'], unique=True)

    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profit_and_loss.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researcher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_researcher_id'), ['researcher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_researcher_id'))
        batch_op.drop_index(batch_op.f('ix_trade_owner_id'))
        batch_op.drop_index(batch_op.f('ix_trade_date'))

    op.drop_table('trade')
    with op.batch_alter_table('researcher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_researcher_researcher_name'))
        batch_op.drop_index(batch_op.f('ix_researcher_email'))

    op.drop_table('researcher')
    op.drop_table('profit_and_loss')
    # ### end Alembic commands ###
